name: Check project

on:
  push:
    branches:
      - main

jobs:
  check-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: psf/black@stable
        with:
          options: '--check'
          src: '.'
          version: 23.12.1
      - uses: chartboost/ruff-action@v1
        with:
          src: './**/*.py'
          version: 0.1.14
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.348
